# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Sporløs"
client_id = "00e912a07daebc4233d6fe3e7e7dd189"
application_url = "https://sporlos.no"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customer_events,read_pixels,write_pixels"
optional_scopes = [ ]
use_legacy_install_flow = false

[webhooks]
api_version = "2026-04"

  [[webhooks.subscriptions]]
  uri = "/webhooks/shopify/compliance"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false

[auth]
redirect_urls = [ ]
